image: atlassian/default-image:2
pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
             - docker build -f ./docker/dockerfiles/DockerfileProd -t cer-api-prod:latest .
             - docker tag cer-api-prod:latest registry-docker.jacidi.com/cer-api-prod:latest
             - docker push registry-docker.jacidi.com/cer-api-prod:latest
      - step:
          name: Deployment Production
          deployment: Production
          trigger: manual
          script:  
             - curl -X POST $prod_server
