image: atlassian/default-image:2
pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
             - docker build -f ./docker/dockerfiles/DockerfileProd -t cer-api:prod .
             - docker tag cer-api:prod registry-docker.jacidi.com/cer-api:prod
             - docker push registry-docker.jacidi.com/cer-api:prod
      - step:
          name: Deployment Production
          deployment: Production
          trigger: manual
          script:  
             - curl -X POST $prod_server
