image: atlassian/default-image:2
pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
             - docker build -f ./docker/dockerfiles/DockerfileProd -t cer-api:prod .
             - docker tag cer-api:prod registry-docker.jacidi.com/cer-api:prod
             - docker push registry-docker.jacidi.com/cer-api:prod
      - step:
          name: Deployment Production
          deployment: production
          trigger: manual
          script:  
             - curl -X POST https://admin-docker.jacidi.com/api/webhooks/2a817106-aff9-4814-8f04-84f3637d08b4
