image: atlassian/default-image:2
pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
             - docker build -f ./docker/dockerfiles/DockerfileProd -t cer-api-prod:latest .
             - docker tag cer-api-prod:latest registry.jacidi.com/cer-api-prod:latest
             - docker push registry.jacidi.com/cer-api-prod:latest
      - step:
          name: Deployment Production
          deployment: Production
          trigger: manual
          script:  
             - curl -X POST $prod_server

    qa:
      - step:
          services:
            - docker
          script:
             - docker build -f ./docker/dockerfiles/DockerfileQA -t cer-api-qa:latest .
             - docker tag cer-api-qa registry-docker.jacidi.com/cer-api-qa
             - docker push registry-docker.jacidi.com/cer-api-api
      - step:
          name: Deployment QA
          deployment: test
          trigger: manual
          script:  
             - curl -X POST $qa_server


    uat:
      - step:
          services:
            - docker
          script:
             - docker build -f ./docker/dockerfiles/DockerfileUAT -t cer-api-uat:latest .
             - docker tag cer-api-uat repo-vzla.jacidi.com/cer-api-uat
             - docker push repo-vzla.jacidi.com/cer-api-uat
      - step:
          name: Deployment UAT
          deployment: staging
          trigger: manual
          script:  
             - curl -X POST $uat_server
